# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 10:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory_manager', '0005_auto_20171026_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=200)),
                ('Vendor', models.CharField(max_length=200)),
                ('MRP', models.IntegerField()),
                ('batch_num', models.IntegerField()),
                ('batch_date', models.DateField(default=datetime.date(2017, 10, 26))),
                ('Quantity', models.IntegerField()),
                ('status', models.CharField(default='PENDING', max_length=200)),
                ('store_manager_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_manager_id', to='inventory_manager.InventoryUser')),
            ],
        ),
    ]
