# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='MRP',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='Quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='batch_num',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='product_id',
            field=models.IntegerField(default=0),
        ),
    ]
