# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 11:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20171026_1059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='store_manager_id',
            new_name='store_manager',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 26, 11, 2, 43, 940634, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 26, 11, 2, 43, 940659, tzinfo=utc)),
        ),
    ]
