# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 11:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_manager', '0005_auto_20171026_0951'),
        ('inventory', '0005_auto_20171026_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_name', models.CharField(max_length=200)),
                ('total_items', models.IntegerField(default=0)),
                ('store_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_manager_id', to='inventory_manager.InventoryUser')),
            ],
        ),
        migrations.RemoveField(
            model_name='inventoryrecord',
            name='store_manager',
        ),
        migrations.AlterField(
            model_name='inventoryrecord',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 26, 11, 28, 14, 47383, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='inventoryrecord',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 26, 11, 28, 14, 47462, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='inventoryrecord',
            name='inventory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='inventory.Inventory'),
        ),
    ]
