# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 11:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20171026_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='inventory_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='inventoryrecord',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 26, 11, 30, 30, 711180, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='inventoryrecord',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 26, 11, 30, 30, 711257, tzinfo=utc)),
        ),
    ]
