# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 12:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20171026_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryrecords',
            name='batch_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='inventoryrecords',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 26, 12, 5, 28, 371974, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='inventoryrecords',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 26, 12, 5, 28, 372057, tzinfo=utc)),
        ),
    ]
