# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_auto_20171026_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryrecords',
            name='batch_date',
            field=models.CharField(default=b'2017-10-26', max_length=100, null=True),
        ),
    ]
