# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_manager', '0005_auto_20171026_0951'),
        ('inventory', '0012_auto_20171026_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='dept_managers_subscribed',
            field=models.ManyToManyField(to='inventory_manager.InventoryUser'),
        ),
    ]
