# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 14:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_manager', '0005_auto_20171026_0951'),
        ('inventory', '0015_auto_20171026_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_name', models.CharField(max_length=200, null=True)),
                ('permission_codename', models.CharField(max_length=200, null=True)),
                ('target_user', models.CharField(max_length=200, null=True)),
                ('store_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_manager', to='inventory_manager.InventoryUser')),
            ],
        ),
    ]
