# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_inventorypermissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryrecords',
            name='id',
            field=models.IntegerField(auto_created=True, default=0, primary_key=True, serialize=False),
        ),
    ]
