# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_auto_20171026_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryrecords',
            name='product_id',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
