# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_auto_20171026_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryrecords',
            name='product_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inventoryrecords',
            name='product_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
