# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_manager', '0002_auto_20171026_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryuser',
            name='role',
            field=models.CharField(help_text='Role , either DEPT_MGR or STORE_MGR', max_length=200, null=True),
        ),
    ]
