# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_manager', '0003_auto_20171026_0314'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryuser',
            name='name',
            field=models.TextField(default='Inventory', max_length=200),
        ),
    ]
