# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_manager', '0004_inventoryuser_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryuser',
            name='role',
        ),
        migrations.AddField(
            model_name='inventoryuser',
            name='is_dept_mgr',
            field=models.BooleanField(default=False, help_text='Checked if the user is department manager'),
        ),
        migrations.AddField(
            model_name='inventoryuser',
            name='is_store_mgr',
            field=models.BooleanField(default=False, help_text='Checked if user is store manager'),
        ),
    ]
